version: '3'
 
services:
  web:
    command: >
      sh -c "pipenv run python manage.py migrate &&
             pipenv run python3 manage.py collectstatic --noinput &&
             pipenv run gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    volumes:
      - ./django_coins:/app
      - static_volume:/app/static
    env_file:
      - ./.env.prod

  collect:
    command: >
      sh -c "pipenv run python manage.py collect_coins"
    volumes:
      - ./django_coins:/app
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/app/static
    depends_on:
      - web

volumes:
  static_volume: