version: '3'
 
services:
  web:
    command: >
      sh -c "pipenv run python manage.py migrate &&
             pipenv run python manage.py runserver 0.0.0.0:8000"
    expose:
      - 8000
    volumes:
      - static_volume:/app/config/static
    env_file:
      - ./.env.prod

  collect:
    command: >
      sh -c "pipenv run pyhton manage.py collect_coins"
    env_file:
      - ./.evn.prod

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/app/config/static
    depends_on:
      - web

volumes:
  static_volume: