# Generated by Django 4.1.3 on 2022-11-06 05:13

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(blank=True, null=True, verbose_name='Индентификатор сообщения')),
                ('status', models.IntegerField(choices=[(0, 'Новое'), (1, 'Отправлено'), (2, 'Завешено')], default=0, verbose_name='Статус')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coins.coin', verbose_name='Монета')),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=200, verbose_name='Паттерн')),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filters', to='coins.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('chat_id', models.IntegerField(unique=True, verbose_name='Идентификатор чата')),
                ('coins', models.ManyToManyField(through='core.CoinUser', to='coins.coin', verbose_name='Монеты')),
                ('filters', models.ManyToManyField(to='core.filter', verbose_name='Паттерны')),
            ],
        ),
        migrations.AddField(
            model_name='coinuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='Пользователь'),
        ),
    ]
