# Generated by Django 4.1.3 on 2022-11-06 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coinuser',
            unique_together={('coin', 'user')},
        ),
    ]
