# Generated by Django 4.1.3 on 2022-11-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.IntegerField(unique=True, verbose_name='Идентификатор чата'),
        ),
    ]
