# Generated by Django 4.1.3 on 2022-11-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_coin_url_alter_coin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='url',
            field=models.URLField(unique=True, verbose_name='Идентификатор монеты'),
        ),
    ]
