# Generated by Django 4.1.3 on 2022-11-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_alter_coin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='url',
            field=models.URLField(unique=True, verbose_name='Url монеты'),
        ),
    ]
