# Generated by Django 4.1.3 on 2022-12-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_filter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='is_unc',
            field=models.BooleanField(default=True, verbose_name='UNC'),
        ),
    ]
