# Generated by Django 4.1.3 on 2022-12-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_filter_is_unc'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unc_pattern',
            field=models.CharField(default='unc|унц|блеск|штемп|без обращ|мешков', max_length=200, verbose_name='UNC Паттерн'),
        ),
    ]
