# Generated by Django 4.1.3 on 2022-12-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='end_date',
            new_name='time_end',
        ),
        migrations.AddField(
            model_name='coin',
            name='time_create',
            field=models.DateField(blank=True, null=True, verbose_name='Дата создания аукцина'),
        ),
    ]
