# Generated by Django 4.1.4 on 2023-01-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_alter_coin_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Url изображения'),
        ),
    ]
